name: my_fancy_project

dependencies:
  - attrs=21.4.0
  - cfgv=3.3.1
  - coverage=6.4.1
  - distlib=0.3.4
  - filelock=3.7.1
  - flake8=4.0.1
  - identify=2.5.1
  - importlib-metadata=4.2.0
  - iniconfig=1.1.1
  - isort=5.10.1
  - mccabe=0.6.1
  - mypy=0.961
  - mypy-extensions=0.4.3
  - nodeenv=1.6.0
  - packaging=21.3
  - pip
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - pre-commit=2.19.0
  - py=1.11.0
  - pycodestyle=2.8.0
  - pyflakes=2.4.0
  - pyparsing=3.0.9
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - python=3.9
  - PyYAML=6.0
  - six=1.16.0
  - toml=0.10.2
  - tomli=2.0.1
  - typed-ast=1.5.4
  - typing-extensions=4.2.0
  - virtualenv=20.14.1
  - zipp=3.8.0
